-- ─────────────────────────────────────────────
-- role_permission: grants a permission to a role.
-- The composite foreign keys keep both sides inside the same application.
-- ─────────────────────────────────────────────
CREATE TABLE role_permission (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id        BIGINT      NOT NULL,
    permission_id  BIGINT      NOT NULL,
    application_id BIGINT      NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     BIGINT,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permission_role
        FOREIGN KEY (role_id, application_id)
        REFERENCES role (id, application_id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission
        FOREIGN KEY (permission_id, application_id)
        REFERENCES permission (id, application_id)
);

COMMENT ON TABLE role_permission IS 'Permission granted to a role inside one application.';
