-- ─────────────────────────────────────────────
-- refresh_token: rotating refresh tokens bound to one access grant.
-- Only the SHA-256 hash is stored; the raw token leaves the server exactly once.
-- token_family groups every rotation of one login, so reuse of a revoked token
-- can revoke the whole family.
-- ─────────────────────────────────────────────
CREATE TABLE refresh_token (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_application_id  BIGINT       NOT NULL,
    token_hash           VARCHAR(255) NOT NULL,
    token_family         VARCHAR(64)  NOT NULL,
    issued_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at           TIMESTAMPTZ  NOT NULL,
    revoked_at           TIMESTAMPTZ,
    replaced_by_token_id BIGINT,
    device_id            VARCHAR(100),
    device_info          VARCHAR(500),
    ip_address           INET,
    user_agent           VARCHAR(500),
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user_application
        FOREIGN KEY (user_application_id) REFERENCES user_application (id) ON DELETE CASCADE,
    CONSTRAINT fk_refresh_token_replaced_by
        FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_token (id)
);

COMMENT ON COLUMN refresh_token.token_family IS 'Random, non-sequential family id shared by every rotation of one login.';
