-- ─────────────────────────────────────────────
-- login_attempt: every authentication attempt, successful or not.
-- security_user_id is nullable because attempts against unknown usernames must
-- also be recorded (that is exactly the interesting case).
-- ─────────────────────────────────────────────
CREATE TABLE login_attempt (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_user_id   BIGINT,
    application_id     BIGINT,
    username_attempted VARCHAR(100) NOT NULL,
    success            BOOLEAN      NOT NULL,
    ip_address         INET,
    user_agent         VARCHAR(500),
    failure_reason     VARCHAR(80),
    attempted_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_login_attempt_user
        FOREIGN KEY (security_user_id) REFERENCES security_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_login_attempt_application
        FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE SET NULL
);

COMMENT ON TABLE login_attempt IS 'Audit trail of authentication attempts, including unknown usernames.';
