-- ─────────────────────────────────────────────
-- password_reset_token: single-use, short-lived reset tokens.
-- Only the SHA-256 hash is stored.
-- ─────────────────────────────────────────────
CREATE TABLE password_reset_token (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_application_id BIGINT       NOT NULL,
    token_hash          VARCHAR(255) NOT NULL,
    requested_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at          TIMESTAMPTZ  NOT NULL,
    used_at             TIMESTAMPTZ,
    invalidated_at      TIMESTAMPTZ,
    ip_address          INET,
    user_agent          VARCHAR(500),
    CONSTRAINT uq_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_token_user_application
        FOREIGN KEY (user_application_id) REFERENCES user_application (id) ON DELETE CASCADE
);

COMMENT ON TABLE password_reset_token IS 'Single-use password reset token, stored only as a hash.';
