-- ─────────────────────────────────────────────
-- security_audit: append-only trail of security-relevant events.
-- The API never updates or deletes rows here.
-- ─────────────────────────────────────────────
CREATE TABLE security_audit (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_user_id BIGINT,
    application_id   BIGINT,
    event_type       VARCHAR(80)   NOT NULL,
    resource         VARCHAR(100),
    resource_id      VARCHAR(100),
    action           VARCHAR(80),
    success          BOOLEAN       NOT NULL DEFAULT TRUE,
    description      VARCHAR(1000),
    metadata         JSONB,
    ip_address       INET,
    user_agent       VARCHAR(500),
    correlation_id   VARCHAR(64),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_security_audit_user
        FOREIGN KEY (security_user_id) REFERENCES security_user (id) ON DELETE SET NULL,
    CONSTRAINT fk_security_audit_application
        FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE SET NULL
);

COMMENT ON TABLE security_audit IS 'Append-only security event log. Never updated or deleted through the API.';
