-- ─────────────────────────────────────────────
-- company: the tenant that owns applications.
-- Every table in this schema uses BIGINT IDENTITY keys and TIMESTAMPTZ dates.
-- ─────────────────────────────────────────────
CREATE TABLE company (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_company_code UNIQUE (code)
);

COMMENT ON TABLE company IS 'Tenant that owns one or more applications.';
