-- ─────────────────────────────────────────────
-- application: a product of a company. Roles, permissions and user access are
-- always scoped to exactly one application.
-- ─────────────────────────────────────────────
CREATE TABLE application (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT       NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_application_company_code UNIQUE (company_id, code),
    CONSTRAINT fk_application_company FOREIGN KEY (company_id) REFERENCES company (id)
);

COMMENT ON TABLE application IS 'Application owned by a company; scope of roles and permissions.';
