-- ─────────────────────────────────────────────
-- profession: master table that classifies people.
-- ─────────────────────────────────────────────
CREATE TABLE profession (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  BIGINT,
    updated_at  TIMESTAMPTZ,
    updated_by  BIGINT,
    CONSTRAINT uq_profession_code UNIQUE (code)
);

COMMENT ON TABLE profession IS 'Master list of professions a person can be classified with.';
