-- ─────────────────────────────────────────────
-- person: personal data. A person can exist without credentials; credentials
-- live in security_user and point back here.
-- ─────────────────────────────────────────────
CREATE TABLE person (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profession_id         BIGINT,
    identification_type   VARCHAR(30)  NOT NULL,
    identification_number VARCHAR(50)  NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    middle_name           VARCHAR(100),
    last_name             VARCHAR(100) NOT NULL,
    second_last_name      VARCHAR(100),
    email                 VARCHAR(254) NOT NULL,
    phone                 VARCHAR(30),
    mobile                VARCHAR(30),
    birth_date            DATE,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT,
    CONSTRAINT uq_person_identification UNIQUE (identification_type, identification_number),
    CONSTRAINT fk_person_profession FOREIGN KEY (profession_id) REFERENCES profession (id)
);

-- An email identifies one person; the comparison is case-insensitive.
CREATE UNIQUE INDEX uq_person_email_lower ON person (LOWER(email));

COMMENT ON TABLE person IS 'Personal data. Exists independently of any login account.';
