-- ─────────────────────────────────────────────
-- security_user: credentials of a person. Named security_user because "user" is
-- a reserved word in PostgreSQL. The password is stored ONLY as an Argon2id hash.
-- ─────────────────────────────────────────────
CREATE TABLE security_user (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id             BIGINT       NOT NULL,
    username              VARCHAR(100) NOT NULL,
    password_hash         VARCHAR(255) NOT NULL,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    locked                BOOLEAN      NOT NULL DEFAULT FALSE,
    locked_until          TIMESTAMPTZ,
    failed_attempts       SMALLINT     NOT NULL DEFAULT 0,
    last_login_at         TIMESTAMPTZ,
    password_changed_at   TIMESTAMPTZ,
    credentials_expired   BOOLEAN      NOT NULL DEFAULT FALSE,
    account_expires_at    TIMESTAMPTZ,
    must_change_password  BOOLEAN      NOT NULL DEFAULT TRUE,
    -- Version counter. Bumped on password, role or state changes to invalidate sessions.
    security_stamp        BIGINT       NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by            BIGINT,
    updated_at            TIMESTAMPTZ,
    updated_by            BIGINT,
    CONSTRAINT uq_security_user_person UNIQUE (person_id),
    CONSTRAINT ck_security_user_failed_attempts CHECK (failed_attempts >= 0),
    CONSTRAINT fk_security_user_person FOREIGN KEY (person_id) REFERENCES person (id)
);

-- Usernames are globally unique and compared case-insensitively.
CREATE UNIQUE INDEX uq_security_user_username_lower ON security_user (LOWER(username));

COMMENT ON COLUMN security_user.password_hash IS 'Full Argon2id encoded string. Never the raw password.';
COMMENT ON COLUMN security_user.security_stamp IS 'Incremented on credential/role/state changes; invalidates issued sessions.';
