-- ─────────────────────────────────────────────
-- user_application: grants one user access to one application, optionally
-- limited to a time window. All authorization hangs off this row.
-- ─────────────────────────────────────────────
CREATE TABLE user_application (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    security_user_id BIGINT      NOT NULL,
    application_id   BIGINT      NOT NULL,
    active           BOOLEAN     NOT NULL DEFAULT TRUE,
    access_start_at  TIMESTAMPTZ,
    access_end_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by       BIGINT,
    updated_at       TIMESTAMPTZ,
    updated_by       BIGINT,
    CONSTRAINT uq_user_application UNIQUE (security_user_id, application_id),
    CONSTRAINT ck_user_application_window
        CHECK (access_end_at IS NULL OR access_start_at IS NULL OR access_end_at > access_start_at),
    -- Composite key targeted by user_role, so a role can never cross applications.
    CONSTRAINT uq_user_application_id_app UNIQUE (id, application_id),
    CONSTRAINT fk_user_application_user FOREIGN KEY (security_user_id) REFERENCES security_user (id),
    CONSTRAINT fk_user_application_application FOREIGN KEY (application_id) REFERENCES application (id)
);

COMMENT ON TABLE user_application IS 'Access grant of one user to one application.';
