-- ─────────────────────────────────────────────
-- role: a named bundle of permissions inside one application.
-- ─────────────────────────────────────────────
CREATE TABLE role (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT       NOT NULL,
    code           VARCHAR(80)  NOT NULL,
    name           VARCHAR(150) NOT NULL,
    description    VARCHAR(500),
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,
    CONSTRAINT uq_role_application_code UNIQUE (application_id, code),
    -- Composite key targeted by user_role and role_permission.
    CONSTRAINT uq_role_id_app UNIQUE (id, application_id),
    CONSTRAINT fk_role_application FOREIGN KEY (application_id) REFERENCES application (id)
);

COMMENT ON TABLE role IS 'Role scoped to one application; grouping of permissions.';
