-- ─────────────────────────────────────────────
-- permission: a fine-grained right, expressed as resource + action
-- (for example PERSON + CREATE) with a stable code (PERSON_CREATE).
-- ─────────────────────────────────────────────
CREATE TABLE permission (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT       NOT NULL,
    code           VARCHAR(120) NOT NULL,
    name           VARCHAR(150) NOT NULL,
    description    VARCHAR(500),
    resource       VARCHAR(100) NOT NULL,
    action         VARCHAR(50)  NOT NULL,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by     BIGINT,
    updated_at     TIMESTAMPTZ,
    updated_by     BIGINT,
    CONSTRAINT uq_permission_application_code UNIQUE (application_id, code),
    CONSTRAINT uq_permission_application_resource_action UNIQUE (application_id, resource, action),
    -- Composite key targeted by role_permission.
    CONSTRAINT uq_permission_id_app UNIQUE (id, application_id),
    CONSTRAINT fk_permission_application FOREIGN KEY (application_id) REFERENCES application (id)
);

COMMENT ON TABLE permission IS 'Fine-grained right scoped to one application.';
