-- ─────────────────────────────────────────────
-- user_role: assigns a role to a user's access grant.
-- application_id is denormalised on purpose: the two composite foreign keys make
-- it impossible to assign a role that belongs to a different application.
-- ─────────────────────────────────────────────
CREATE TABLE user_role (
    id                  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_application_id BIGINT      NOT NULL,
    role_id             BIGINT      NOT NULL,
    application_id      BIGINT      NOT NULL,
    active              BOOLEAN     NOT NULL DEFAULT TRUE,
    valid_from          TIMESTAMPTZ,
    valid_until         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          BIGINT,
    CONSTRAINT uq_user_role UNIQUE (user_application_id, role_id),
    CONSTRAINT ck_user_role_window
        CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until > valid_from),
    CONSTRAINT fk_user_role_user_application
        FOREIGN KEY (user_application_id, application_id)
        REFERENCES user_application (id, application_id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id, application_id)
        REFERENCES role (id, application_id)
);

COMMENT ON TABLE user_role IS 'Role assignment; composite FKs keep the role inside the access grant application.';
